trigger:
- refs/pulls/6/merge

pr: 
- main


extends:
  template: template.yml
  parameters:
    stages:
    - stage: stage1
      displayName: Stage 1
      jobs:
      - job: job1_1
        displayName: Stage 1, job1.1
        steps:
        - script: echo "Im job 1.1"
        - script: echo $(Build.SourceBranch)
