trigger:
- main

pool:
  vmImage: ubuntu-latest

extends:
  template: template.yml
  parameters:
    stages:
    - stage: stage1
      displayName: Stage 1
      jobs:
      - job: job1_1
        displayName: Stage 1, job1.1
        steps:
        - script: echo "Im job 1.1"
      - job: job1_2
        displayName: Stage 1, job1.2
        steps:
        - script: echo "Im job 1.2"
    - stage: stage2
      displayName: Stage 2
      jobs:
      - job: job2_1
        displayName: Stage 2, job2.1
        steps:
        - script: echo "Im job 2.1"
      - job: job2_2
        displayName: Stage 2, job2.2
        steps:
        - script: echo "Im job 2.2"         
